# Generated by Django 2.0.6 on 2018-10-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('latitud', models.CharField(max_length=30)),
                ('estadogeo', models.CharField(max_length=30)),
            ],
        ),
    ]
